import { REVIEW_KIND_OPTIONS, REVIEW_SCORE_OPTIONS, REVIEW_TAG_OPTIONS, REVIEW_WRITER_COPY } from '@/features/review/const/reviewSubmission.const'

export const REVIEW_WRITER_PANEL_COPY = REVIEW_WRITER_COPY
export { REVIEW_KIND_OPTIONS, REVIEW_SCORE_OPTIONS, REVIEW_TAG_OPTIONS }
