import {
    REVIEW_KIND_OPTIONS,
    REVIEW_RATING_OPTIONS,
    REVIEW_TAG_OPTIONS,
    REVIEW_WRITER_COPY,
} from '@/features/review/const/reviewSubmission.const'

export const MODAL_CLOSE_ANIMATION_MS = 220
export const REVIEW_RATING_MIN = 0.5
export const REVIEW_RATING_MAX = 5
export const REVIEW_RATING_STEP = 0.5

export const REVIEW_WRITER_PANEL_COPY = REVIEW_WRITER_COPY
export { REVIEW_KIND_OPTIONS, REVIEW_RATING_OPTIONS, REVIEW_TAG_OPTIONS }
